---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rhtap-installer-e2e
spec:
  description: |-
    This pipeline automates the process of running end-to-end tests for RHTAP
    using a ROSA (Red Hat OpenShift Service on AWS) cluster. The pipeline provisions
    the ROSA cluster, installs RHTAP using the installer, runs the tests, collects artifacts,
    and finally deprovisions the ROSA cluster.
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: test-name
      description: 'The name of the test corresponding to a defined Konflux integration test.'
      default: ''
    - name: ocp-version
      description: 'The OpenShift version to use for the ephemeral cluster deployment.'
      default: '4.15.9'
      type: string
    - name: test-event-type
      description: 'Indicates if the test is triggered by a Pull Request or Push event.'
      default: 'none'
    - name: region
      description: 'The AWS region to provision the ROSA cluster. Default is us-west-2.'
      default: 'us-west-2'
    - name: aws-secrets
      description: 'The AWS secrets used for provisioning the ROSA cluster.'
      default: 'aws-secrets'
    - name: replicas
      description: 'The number of replicas for the cluster nodes.'
      default: '3'
    - name: machine-type
      description: 'The type of machine to use for the cluster nodes.'
      default: 'm5.2xlarge'
    - name: oras-container
      default: 'quay.io/konflux-qe-incubator/konflux-qe-oci-storage'
      description: The ORAS container used to store all test artifacts.
    - name: AWS_OIDC_CONFIG_ID
      description: 'The AWS OIDC config ID used for provisioning the ROSA cluster.'
    - name: OPERATOR_ROLES_PREFIX
      description: 'The prefix for the operator roles.'
    - name: SUBNET_IDS
      description: 'The subnet IDs for the ROSA cluster.'
    - name: INSTALL_ROLE_ARN
      description: 'The role ARN for the install role.'
    - name: SUPPORT_ROLE_ARN
      description: 'The role ARN for the support role.'
    - name: WORKER_ROLE_ARN
      description: 'The role ARN for the worker role.'
  tasks:
    - name: rosa-hcp-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/rosa/hosted-cp/rosa-hcp-metadata/rosa-hcp-metadata.yaml
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/test-metadata/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: oras-container
          value: $(params.oras-container)
        - name: test-name
          value: $(context.pipelineRun.name)
    - name: provision-rosa
      when:
        - input: "$(tasks.test-metadata.results.test-event-type)"
          operator: in
          values: ["pull_request"]
      runAfter:
        - rosa-hcp-metadata
        - test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/xinredhat/konflux-qe-definitions.git
          - name: revision
            value: RHTAP-2737
          - name: pathInRepo
            value: common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
      params:
        - name: cluster-name
          value: "$(tasks.rosa-hcp-metadata.results.cluster-name)"
        - name: ocp-version
          value: "$(params.ocp-version)"
        - name: region
          value: "$(params.region)"
        - name: replicas
          value: "$(params.replicas)"
        - name: machine-type
          value: "$(params.machine-type)"
        - name: aws-secrets
          value: "$(params.aws-secrets)"
        - name: AWS_OIDC_CONFIG_ID
          value: "$(params.AWS_OIDC_CONFIG_ID)"
        - name: OPERATOR_ROLES_PREFIX
          value: "$(params.OPERATOR_ROLES_PREFIX)"
        - name: SUBNET_IDS
          value: "$(params.SUBNET_IDS)"
        - name: INSTALL_ROLE_ARN
          value: "$(params.INSTALL_ROLE_ARN)"
        - name: SUPPORT_ROLE_ARN
          value: "$(params.SUPPORT_ROLE_ARN)"
        - name: WORKER_ROLE_ARN
          value: "$(params.WORKER_ROLE_ARN)"
    - name: rhtap-install
      when:
        - input: "$(tasks.test-metadata.results.test-event-type)"
          operator: in
          values: ["pull_request"]
      runAfter:
        - provision-rosa
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/rhtap-installer.git
          - name: revision
            value: release-1.0.2
          - name: pathInRepo
            value: .tekton/integration-tests/tasks/rhtap-installer.yaml
      params:
        - name: ocp-login-command
          value: "$(tasks.provision-rosa.results.ocp-login-command)"
        - name: git-url
          value: "$(tasks.test-metadata.results.git-url)"
        - name: git-revision
          value: "$(tasks.test-metadata.results.git-revision)"
    - name: sprayproxy-provision
      when:
        - input: "$(tasks.test-metadata.results.test-event-type)"
          operator: in
          values: ["pull_request"]
      runAfter:
        - rhtap-install
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/sprayproxy/sprayproxy-provision/sprayproxy-register-server.yaml
      params:
        - name: ocp-login-command
          value: "$(tasks.provision-rosa.results.ocp-login-command)"
    - name: rhtap-e2e-tests
      when:
        - input: "$(tasks.test-metadata.results.test-event-type)"
          operator: in
          values: ["pull_request"]
      runAfter:
        - sprayproxy-provision
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-test/rhtap/rhtap-e2e/task/rhtap-e2e-runner.yaml
      params:
        - name: test-name
          value: $(context.pipelineRun.name)
        - name: ocp-login-command
          value: "$(tasks.provision-rosa.results.ocp-login-command)"
        - name: oras-container
          value: "$(tasks.test-metadata.results.oras-container)"
  finally:
    - name: collect-install-failure
      when:
        - input: "$(tasks.rhtap-install.status)"
          operator: in
          values: ["Failed"]
      params:
        - name: ocp-login-command
          value: "$(tasks.provision-rosa.results.ocp-login-command)"
      taskSpec:
        params:
          - name: ocp-login-command
            type: string
        steps:
          - name: collect-install-failure
            image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
            script: |
              #!/bin/sh
              echo $(params.ocp-login-command)
              $(params.ocp-login-command)
              if [ "$(kubectl -n rhtap get job rhtap-installer-configure -o name --ignore-not-found | wc -l)" = "1" ]; then
                echo "[INFO]Extracting logs from job rhtap-installer-configure..."
                kubectl -n rhtap logs job/rhtap-installer-configure --all-containers=true
              fi

              if [ "$(kubectl -n rhtap get job rhtap-installer-test -o name --ignore-not-found | wc -l)" = "1" ]; then
                echo "[INFO]Extracting logs from job rhtap-installer-test..."
                kubectl -n rhtap logs job/rhtap-installer-test --all-containers=true
              fi
    - name: deprovision-rosa-collect-artifacts
      when:
        - input: "$(tasks.test-metadata.results.test-event-type)"
          operator: in
          values: ["pull_request"]
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
      params:
        - name: test-name
          value: $(context.pipelineRun.name)
        - name: ocp-login-command
          value: "$(tasks.provision-rosa.results.ocp-login-command)"
        - name: oras-container
          value: "$(tasks.test-metadata.results.oras-container)"
        - name: pull-request-author
          value: "$(tasks.test-metadata.results.pull-request-author)"
        - name: git-revision
          value: "$(tasks.test-metadata.results.git-revision)"
        - name: pull-request-number
          value: "$(tasks.test-metadata.results.pull-request-number)"
        - name: git-repo
          value: "$(tasks.test-metadata.results.git-repo)"
        - name: git-org
          value: "$(tasks.test-metadata.results.git-org)"
        - name: cluster-name
          value: "$(tasks.rosa-hcp-metadata.results.cluster-name)"
        - name: region
          value: "$(params.region)"
        - name: aws-secrets
          value: "$(params.aws-secrets)"
    - name: sprayproxy-deprovision
      when:
        - input: "$(tasks.test-metadata.results.test-event-type)"
          operator: in
          values: ["pull_request"]
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/sprayproxy/sprayproxy-deprovision/sprayproxy-unregister-server.yaml
